language: julia

jobs:
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        # Install required packages for coverage and documentation
        - julia --project -e 'import Pkg; Pkg.add("Coverage");
            Pkg.add("Documenter"); Pkg.add("DocumenterTools");'
        - julia --project=docs/ -e 'using Pkg;
            Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl

        # Submit test coverage report
        - julia --project -e 'using Coverage;
            Coveralls.submit(Coveralls.process_folder())'

      after_success:
        - julia --project ./docs/make.jl
        
      coveralls: true

    - stage: "Tests"
      install:
        - pip3 install scipy
      julia: 1.4
      os:
        - linux
        - osx
        - windows
      notifications:
        email: false
      script:
        - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build();
            Pkg.activate("."); Pkg.test("IBZ"; coverage=true)'
